/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Step4;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Vaty
 */
public class Application2 extends javax.swing.JFrame {

    /* Variables */
    Socket ssm; 
    
    PrintStream pms;
    
    boolean possedeFich;
    
    /**
     * Creates new form Application1
     */
    public Application2() {
        initComponents();
        initWindowListener();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filec_fichier = new javax.swing.JFileChooser();
        option_servcli = new javax.swing.JOptionPane();
        option_complet = new javax.swing.JOptionPane();
        lbl_possedezvous = new javax.swing.JLabel();
        btn_Oui = new javax.swing.JButton();
        btn_non = new javax.swing.JButton();
        lbl_nomfich = new javax.swing.JLabel();
        btn_valider = new javax.swing.JButton();
        btn_annuler = new javax.swing.JButton();
        txt_ipserv = new javax.swing.JTextField();
        lbl_ipserv = new javax.swing.JLabel();
        lbl_possedefich = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Application 2");
        setAlwaysOnTop(true);

        lbl_possedezvous.setText("Possédez-vous le fichier");

        btn_Oui.setText("Oui");
        btn_Oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OuiActionPerformed(evt);
            }
        });

        btn_non.setText("Non");
        btn_non.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nonActionPerformed(evt);
            }
        });

        lbl_nomfich.setToolTipText("");

        btn_valider.setText("Valider");
        btn_valider.setEnabled(false);
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        btn_annuler.setText("Annuler");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        txt_ipserv.setToolTipText("");

        lbl_ipserv.setText("Entrez le nom ou l'ip du serveur Main");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_ipserv)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 219, Short.MAX_VALUE)
                        .addComponent(btn_annuler)))
                .addGap(18, 18, 18)
                .addComponent(btn_valider)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Oui)
                                .addGap(18, 18, 18)
                                .addComponent(btn_non)
                                .addGap(40, 40, 40)
                                .addComponent(lbl_possedefich))
                            .addComponent(lbl_possedezvous)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nomfich, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ipserv))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_possedezvous)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Oui)
                    .addComponent(btn_non)
                    .addComponent(lbl_possedefich))
                .addGap(33, 33, 33)
                .addComponent(lbl_nomfich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lbl_ipserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ipserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_annuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initWindowListener(){
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                try {
                    pms.println("fin connexion");
                    System.exit(0);
                }catch (Exception ex){
                    System.exit(0);
                }
            }
        });
    }
    private void btn_OuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OuiActionPerformed
        filec_fichier.setVisible(true);
        filec_fichier.showOpenDialog(this);
        lbl_nomfich.setText(filec_fichier.getSelectedFile().getName());
        btn_valider.setEnabled(true);
        lbl_possedefich.setText("Vous possédez le fichier");
        possedeFich = true;
        
    }//GEN-LAST:event_btn_OuiActionPerformed

    private void btn_nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nonActionPerformed
        // Si on possède pas le fichier on devient client et on cherche
        // à reconstituer le ficher
        //
        btn_valider.setEnabled(true);
        lbl_possedefich.setText("Vous possédez pas le fichier");
        possedeFich = false;
        //
        
    }//GEN-LAST:event_btn_nonActionPerformed

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        lbl_nomfich.setText("");
        lbl_possedefich.setText("");
        txt_ipserv.setText("");
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        
        try {
            if (!possedeFich) {
                boolean finRecup;
                option_servcli.showMessageDialog(null, "Vous devenez client "
                        + "et recevrez des blocs de donnees","Information", JOptionPane.INFORMATION_MESSAGE);
                Client cli = new Client(2,txt_ipserv.getText());
                finRecup = cli.recupererFichier();
                while(!finRecup){}
                 option_complet.showMessageDialog(null, "Fichier Reconstitue dans le dossier "
                        + "C:\\BitTorrentStep4Appli2, Vous devenez serveur qui envoie des blocs de données",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                cli.toServeur();
                
            } else {
                option_servcli.showMessageDialog(null, "Vous devenez serveur "
                        + "et envoyez des blocs de donnees","Information", JOptionPane.INFORMATION_MESSAGE);
                /// On possède le fichier, on initalise le serveur
                ServerSocket ssg = new ServerSocket(40001);
                ServerSocket ssB = new ServerSocket(39001);
                
                ssm = new Socket(txt_ipserv.getText(),40010);
                
                pms = new PrintStream(ssm.getOutputStream());
                
                pms.println(2);
                pms.println("possede");
                // On crée un thread pour chaque applications qui se connecteront à ce serveur
                while (true) {
                     this.requestFocus();
                    Socket sss = ssg.accept();
                    Socket sssB = ssB.accept();
                    Thread t = new Thread(new ServeurThread(sss,sssB, filec_fichier.getSelectedFile().toString()
                            ,filec_fichier.getSelectedFile().getName()));
                    t.start();
                }
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btn_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application2().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Oui;
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_non;
    private javax.swing.JButton btn_valider;
    private javax.swing.JFileChooser filec_fichier;
    private javax.swing.JLabel lbl_ipserv;
    private javax.swing.JLabel lbl_nomfich;
    private javax.swing.JLabel lbl_possedefich;
    private javax.swing.JLabel lbl_possedezvous;
    private javax.swing.JOptionPane option_complet;
    private javax.swing.JOptionPane option_servcli;
    private javax.swing.JTextField txt_ipserv;
    // End of variables declaration//GEN-END:variables
}

